# Sử dụng image Python nhẹ
FROM python:3.9-slim

# Đặt thư mục làm việc trong container
WORKDIR /app

# Ép Python in log ra ngay lập tức, không dùng bộ đệm
ENV PYTHONUNBUFFERED=1

RUN pip install confluent-kafka

# Copy thư mục data (chứa edges_schema.json) và thư mục code vào container
COPY data/ ./data/
COPY data_ingestion/ ./data_ingestion/

# Lệnh khởi chạy tự động khi container bật lên
CMD ["python", "data_ingestion/bot_simulation.py"]