FROM python:3.9-slim

WORKDIR /app

# Cài đặt Java (Bắt buộc để chạy được PySpark)
RUN apt-get update && apt-get install -y default-jre && rm -rf /var/lib/apt/lists/*

# Cài đặt các thư viện cần thiết
RUN pip install --default-timeout=1000 --no-cache-dir pyspark redis confluent-kafka shapely

# Copy thư mục chung và thư mục code
COPY data/ ./data/
COPY stream_processing/ ./stream_processing/

CMD ["python", "stream_processing/spark_kafka_consumer.py"]