FROM python:3.11-slim

WORKDIR /app

COPY stream_processing/ ./stream_processing/

RUN pip install networkx pymongo redis confluent-kafka

COPY data/ ./data/
COPY route_optimization/ ./route_optimization/

CMD ["python", "route_optimization/route_optimizer.py"]