FROM python:3.9-slim

WORKDIR /app

COPY stream_processing/redis_manager.py .

RUN pip install networkx pymongo redis confluent-kafka

COPY data/ ./data/
COPY route_optimization/ ./route_optimization/

CMD ["python", "route_optimization/test_optimizer.py"]